require("Useful Lua Tools")

print("=== BigNum Power Function Tests ===\n")

print("Test 1: Positive whole exponent")
local a = bignum.new("2")
local result = bignum.pow(a, 10)
print("2^10 = " .. bignum.to_string(result))
print()

print("Test 2: Negative exponent")
local b = bignum.new("2")
local result2 = bignum.pow(b, -3, 5)
print("2^-3 = " .. bignum.to_string(result2))
print()

print("Test 3: Fractional exponent (square root)")
local c = bignum.new("16")
local result3 = bignum.pow(c, 0.5, 6)
print("16^0.5 = " .. bignum.to_string(result3))
print()

print("Test 4: Fractional exponent (cube root)")
local d = bignum.new("8")
local result4 = bignum.pow(d, 1/3, 6)
print("8^(1/3) = " .. bignum.to_string(result4))
print()

print("Test 5: Mixed - 4^2.5")
local e = bignum.new("4")
local result5 = bignum.pow(e, 2.5, 6)
print("4^2.5 = " .. bignum.to_string(result5))
print()

print("Test 6: Large number with positive exponent")
local f = bignum.new("123456789")
local result6 = bignum.pow(f, 3)
print("123456789^3 = " .. bignum.to_string(result6))
print()

print("Test 7: Decimal base number")
local g = bignum.new("1.5")
local result7 = bignum.pow(g, 3, 6)
print("1.5^3 = " .. bignum.to_string(result7))
print()

print("=== Base58 Encoding/Decoding Tests (using BigNum library) ===\n")

print("Test 1: Simple text encoding/decoding")
local text1 = "Hello World"
local encoded1 = cryptography.text_to_base58(text1)
local decoded1 = cryptography.base58_to_text(encoded1)
print("Original: " .. text1)
print("Encoded: " .. encoded1)
print("Decoded: " .. decoded1)
print("Match: " .. tostring(text1 == decoded1))
print()

print("Test 2: Empty string")
local text2 = ""
local encoded2 = cryptography.text_to_base58(text2)
local decoded2 = cryptography.base58_to_text(encoded2)
print("Original: (empty)")
print("Encoded: " .. encoded2)
print("Decoded: " .. decoded2)
print("Match: " .. tostring(text2 == decoded2))
print()

print("Test 3: Leading zeros")
local text3 = string.char(0, 0, 72, 101, 108, 108, 111)
local encoded3 = cryptography.text_to_base58(text3)
local decoded3 = cryptography.base58_to_text(encoded3)
print("Original: (2 null bytes + 'Hello')")
print("Encoded: " .. encoded3)
print("Decoded match: " .. tostring(text3 == decoded3))
print()

print("Test 4: Large number encoding")
local text4 = "The quick brown fox jumps over the lazy dog"
local encoded4 = cryptography.text_to_base58(text4)
local decoded4 = cryptography.base58_to_text(encoded4)
print("Original: " .. text4)
print("Encoded: " .. encoded4)
print("Decoded: " .. decoded4)
print("Match: " .. tostring(text4 == decoded4))
print()

print("Test 5: Binary data")
local text5 = string.char(255, 254, 253, 1, 2, 3)
local encoded5 = cryptography.text_to_base58(text5)
local decoded5 = cryptography.base58_to_text(encoded5)
print("Original: (binary bytes 255,254,253,1,2,3)")
print("Encoded: " .. encoded5)
print("Decoded match: " .. tostring(text5 == decoded5))
print()
